// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {hid} from '../models';

export function GetHIDDevices():Promise<Array<hid.DeviceInfo>>;

export function Greet(arg1:string):Promise<string>;
